version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    
    reviewers:
      - "Tam1SH"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      
    open-pull-requests-limit: daily